dependencies:
  - python=3.6
  - pip:
    - opencv-python==4.3.0.38
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - tensorflow==2.3.0
    - keras==2.4.0
